### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by Arnau478** [Fuechs/Fux#2]
Hi, I came across this repository, and thought I really want to contribute. The thing is that I couldn't find any kind of contributing-related information. So, are contributions accepted or is it too early to do so?

**Comment by Fuechs** [comment]
Thanks for your interest! I honestly did not consider that anyone would want to contribute to this project. 
It may take some time for me to inform myself about contribution guidelines and what they should include (I also need to get more familiar with Github in general). I'll add them in the future.
For the moment, I must ask you to wait until I get back to you with more information (and clean up my code).
Thank you for bringing this to my attention.

**Comment by Arnau478** [comment]
Sure thing, I'm eager to help with the project wherever I can, but I'll wait for the guidelines.

**Comment by Fuechs** [comment]
I added some guidelines for contributing now. Please note that these are incomplete and will change in the future (Especially regarding legal matters). 
I'll leave this issue open in case you have any more questions, otherwise you can close it.
