### ISSUE TITLE
I found some small errors. 

### ISSUE THREAD

**Issue by mauro-balades** [Fuechs/Fux#5]
1. Binary operators don't support floating points
2. You create an alloca each time a variable is declared but it should really just be allocated at the beginning of the function and then store when you encounter the variable

**Comment by Fuechs** [comment]
The binary operations will be fixed as soon as the current [LLVMWrapper](https://github.com/Fuechs/Fux/blob/7f4d5c0a4dbc594a16aaa0ff4689644d4a3d9e79/src/backend/generator/wrapper.hpp#L33) gets replaced with the [Eisdrache Wrapper](https://github.com/fuechs/eisdrache) I am currently working on.
Could you please explain what you mean by the second error?

**Comment by mauro-balades** [comment]
I saw that you where creating a new alloca instruction when you encounter a variable statement. This can be a trouble maker because, for example, you might not want to allocate new variables each iteration of a loop. What I recommend you to do is to create some sort of list where you can keep all of the variables stored into the current function and the first thing you will need to do in the ir is to allocate them. Note that when I saw allocate, I don't mean store. You store the value when you encounter the variable statement.

**Comment by Fuechs** [comment]
Thanks a lot! I will be working on implementing this.

**Comment by Fuechs** [comment]
Closing this issue since binary operations got implemented in the Eisdrache Wrapper ([Commit](https://github.com/Fuechs/eisdrache/commit/7bd3d33deb923483e8142cedbf978a8afab67d56)).
